"""PostgreSQL persistence for durable serverless reservations.

Lock the restaurant row before counting booked guests, so concurrent Vercel
instances cannot exceed capacity on the same restaurant/date/time slot.
"""
import psycopg
from psycopg.rows import dict_row
from fastapi import HTTPException
from app.database import SAMPLE_RESTAURANTS

SCHEMA = (
    "CREATE SCHEMA IF NOT EXISTS mesa",
    """CREATE TABLE IF NOT EXISTS mesa.restaurants (
        id INTEGER PRIMARY KEY, name TEXT NOT NULL,
        capacity INTEGER NOT NULL CHECK (capacity > 0)
    )""",
    """CREATE TABLE IF NOT EXISTS mesa.reservations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        restaurant_id INTEGER NOT NULL REFERENCES mesa.restaurants(id),
        reservation_date DATE NOT NULL,
        reservation_time TEXT NOT NULL,
        guests INTEGER NOT NULL CHECK (guests > 0),
        status TEXT NOT NULL DEFAULT 'active'
            CHECK (status IN ('active', 'cancelled')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )""",
    """CREATE INDEX IF NOT EXISTS idx_mesa_reservation_slot
        ON mesa.reservations
        (restaurant_id, reservation_date, reservation_time, status)""",
)
FIELDS = ("id, restaurant_id, reservation_date AS date, "
          "reservation_time AS time, guests, status")


def connection(database_url):
    return psycopg.connect(database_url, row_factory=dict_row, connect_timeout=10)


def initialize(database_url):
    with connection(database_url) as conn:
        for statement in SCHEMA:
            conn.execute(statement)
        for restaurant in SAMPLE_RESTAURANTS:
            conn.execute(
                """INSERT INTO mesa.restaurants(id, name, capacity)
                   VALUES (%s, %s, %s) ON CONFLICT (id) DO NOTHING""",
                restaurant,
            )


def occupied(conn, restaurant_id, date, time):
    row = conn.execute(
        """SELECT COALESCE(SUM(guests), 0) AS occupied
           FROM mesa.reservations WHERE restaurant_id = %s
           AND reservation_date = %s AND reservation_time = %s
           AND status = 'active'""",
        (restaurant_id, date, time),
    ).fetchone()
    return int(row["occupied"])


def restaurants(database_url, date=None, time=None, guests=1):
    with connection(database_url) as conn:
        entries = conn.execute(
            "SELECT id, name, capacity FROM mesa.restaurants ORDER BY id"
        ).fetchall()
        if date is not None and time is not None:
            for entry in entries:
                remaining = entry["capacity"] - occupied(
                    conn, entry["id"], date, time
                )
                entry["available_seats"] = remaining
                entry["can_accommodate"] = remaining >= guests
        return entries


def create(database_url, payload):
    with connection(database_url) as conn:
        restaurant = conn.execute(
            "SELECT capacity FROM mesa.restaurants WHERE id = %s FOR UPDATE",
            (payload.restaurant_id,),
        ).fetchone()
        if restaurant is None:
            raise HTTPException(status_code=404, detail="restaurant not found")
        if occupied(conn, payload.restaurant_id, payload.date, payload.time) + payload.guests > restaurant["capacity"]:
            raise HTTPException(
                status_code=409,
                detail="not enough seats available for this date and time",
            )
        return conn.execute(
            """INSERT INTO mesa.reservations
               (restaurant_id, reservation_date, reservation_time, guests)
               VALUES (%s, %s, %s, %s)
               RETURNING id, restaurant_id, reservation_date AS date,
                         reservation_time AS time, guests, status""",
            (payload.restaurant_id, payload.date, payload.time, payload.guests),
        ).fetchone()


def get(database_url, reservation_id):
    with connection(database_url) as conn:
        reservation = conn.execute(
            f"SELECT {FIELDS} FROM mesa.reservations WHERE id = %s",
            (reservation_id,),
        ).fetchone()
    if reservation is None:
        raise HTTPException(status_code=404, detail="reservation not found")
    return reservation


def cancel(database_url, reservation_id):
    with connection(database_url) as conn:
        reservation = conn.execute(
            "SELECT status FROM mesa.reservations WHERE id = %s FOR UPDATE",
            (reservation_id,),
        ).fetchone()
        if reservation is None:
            raise HTTPException(status_code=404, detail="reservation not found")
        if reservation["status"] == "cancelled":
            raise HTTPException(status_code=409, detail="reservation already cancelled")
        conn.execute(
            "UPDATE mesa.reservations SET status = 'cancelled' WHERE id = %s",
            (reservation_id,),
        )
